version: "3"

networks:
  pg_db:
    external: false

services:
  lector:
    image: lector:0.1
    build:
      context: docker/lector
      dockerfile: Dockerfile.dev
    networks:
      - pg_db
    env_file:
      - docker/lector/dev.env
    volumes:
      - ./src:/lector
      - ./osm_data:/osm_data
      - ./configs:/configs
      - ./test:/test
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 0.0.0.0:8888:80

  graphhopper:
    image: graphhopper:0.12.0.0-willy
    build:
      context: ./docker/graphhopper/graphhopper-0.12.0
      dockerfile: Dockerfile
    command: /data/data.osm
    volumes:
      - ./osm_data:/data
      - ./docker/graphhopper/config.yml:/graphhopper/config.yml
    ports:
      - 8989:8989
