FROM alpine:3.10
ADD ["requirements.txt", "/requirements.txt"]
ENV PROJ_DIR /usr
RUN apk upgrade --update && \
    apk add --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
        python3 \
        python3-dev \
        build-base \
        cython \
        gdal \
        gdal-dev \
        py-gdal \
        geos \
        py3-pandas \
        py-numpy-dev \
        proj \
        proj-util \
        proj-dev \
        freetype-dev \
        py3-psycopg2 && \
        rm -rf /var/cache/apk/*
RUN pip3 install -r /requirements.txt && rm /requirements.txt
WORKDIR /lector
EXPOSE 80

ENTRYPOINT ["python3", "manage.py"]
CMD ["runserver", "0.0.0.0:80"]
